export class NGFControlStyleTokens {
  static readonly FORM_CONTROL_MIN_HEIGHT: number = 40;
  static readonly FORM_CONTROL_RADIUS: number = 12;
  static readonly FORM_CONTROL_FONT_SIZE: number = 14;
  static readonly DENSE_BUTTON_HEIGHT: number = 40;
  static readonly NORMAL_BUTTON_HEIGHT: number = 44;
  static readonly DENSE_BUTTON_RADIUS: number = 20;
  static readonly NORMAL_BUTTON_RADIUS: number = 22;
  static readonly DENSE_BUTTON_FONT_SIZE: number = 12;
  static readonly SEGMENT_BUTTON_FONT_SIZE: number = 13;
}
