export class NGFHdsDemoRouteName {
  static readonly SHOWCASE: string = 'ngf.hds.showcase';
  static readonly OFFICIAL_NAVIGATION: string = 'ngf.hds.official.navigation';
  static readonly OFFICIAL_NAVIGATION_OVERVIEW: string = 'ngf.hds.official.navigation.overview';
  static readonly OFFICIAL_NAVIGATION_MATERIAL: string = 'ngf.hds.official.navigation.material';
  static readonly OFFICIAL_NAVIGATION_EFFECT: string = 'ngf.hds.official.navigation.effect';
}
