export class NGFHdsDemoRouteName {
  static readonly SHOWCASE: string = 'ngf.hds.showcase';
  static readonly OFFICIAL_NAVIGATION: string = 'ngf.hds.official.navigation';
  static readonly OFFICIAL_NAVIGATION_OVERVIEW: string = 'ngf.hds.official.navigation.overview';
  static readonly OFFICIAL_NAVIGATION_MATERIAL: string = 'ngf.hds.official.navigation.material';
  static readonly OFFICIAL_NAVIGATION_EFFECT: string = 'ngf.hds.official.navigation.effect';
  static readonly DEMO_SECURITY_PERF: string = 'ngf.demo.security.perf';
  static readonly DEMO_DATA_STORAGE: string = 'ngf.demo.data.storage';
  static readonly DEMO_WORKFLOW: string = 'ngf.demo.workflow';
  static readonly DEMO_DEVICE_DISPLAY: string = 'ngf.demo.device.display';
  static readonly SYSTEM_RESOURCE_PREVIEW: string = 'ngf.system.resource.preview';
  static readonly TASK_MANAGER: string = 'ngf.task.manager';
  static readonly DEMO_ERROR_RECOVERY: string = 'ngf.demo.error.recovery';
  static readonly DEMO_SYNC_MANAGER: string = 'ngf.demo.sync.manager';
  static readonly CAPABILITY_NETWORK: string = 'ngf.capability.network';
  static readonly CAPABILITY_RDB: string = 'ngf.capability.rdb';
  static readonly CAPABILITY_WEB_BRIDGE: string = 'ngf.capability.web.bridge';
  static readonly CAPABILITY_SECURITY: string = 'ngf.capability.security';
  static readonly CAPABILITY_HARDWARE: string = 'ngf.capability.hardware';
  static readonly CAPABILITY_MEDIA: string = 'ngf.capability.media';
}



