export class NGFHdsDemoRouteName {
  static readonly SHOWCASE: string = 'ngf.hds.showcase';
  static readonly OFFICIAL_NAVIGATION: string = 'ngf.hds.official.navigation';
  static readonly OFFICIAL_NAVIGATION_OVERVIEW: string = 'ngf.hds.official.navigation.overview';
  static readonly OFFICIAL_NAVIGATION_MATERIAL: string = 'ngf.hds.official.navigation.material';
  static readonly OFFICIAL_NAVIGATION_EFFECT: string = 'ngf.hds.official.navigation.effect';
  static readonly DEMO_SECURITY_PERF: string = 'ngf.demo.security.perf';
  static readonly DEMO_DATA_STORAGE: string = 'ngf.demo.data.storage';
  static readonly DEMO_WORKFLOW: string = 'ngf.demo.workflow';
  static readonly DEMO_DEVICE_DISPLAY: string = 'ngf.demo.device.display';
  static readonly SYSTEM_RESOURCE_PREVIEW: string = 'ngf.system.resource.preview';
  static readonly TASK_MANAGER: string = 'ngf.task.manager';
}



